In [2]:
import pandas as pd
df=pd.read_csv("Finance_data.csv")
df.head()

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Female,34,Yes,1,2,5,3,7,6,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines
1,Female,23,Yes,4,3,2,1,5,6,7,...,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants
2,Male,30,Yes,3,6,4,2,5,1,7,...,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television
3,Male,22,Yes,2,1,3,7,6,4,5,...,Less than 1 year,Daily,10%-20%,Equity,Retirement Plan,Dividend,Fund Diversification,Tax Incentives,High Interest Rates,Internet
4,Female,24,No,2,1,3,6,4,5,7,...,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Risk Free,Internet

In [11]:
print(df)

    gender  age Investment_Avenues  Mutual_Funds  Equity_Market  Debentures  \
0   Female   34                Yes             1              2           5
1   Female   23                Yes             4              3           2
2     Male   30                Yes             3              6           4
3     Male   22                Yes             2              1           3
4   Female   24                 No             2              1           3
5   Female   24                 No             7              5           4
6   Female   27                Yes             3              6           4
7     Male   21                Yes             2              3           7
8     Male   35                Yes             2              4           7
9     Male   31                Yes             1              3           7
10  Female   35                Yes             2              4           7
11    Male   29                Yes             2              5           7
12  Female   21                 No             1              2           3
13  Female   28                Yes             2              3           7
14  Female   25                Yes             2              3           7
15    Male   27                Yes             2              3           7
16  Female   28                Yes             3              2           7
17    Male   27                Yes             3              2           7
18    Male   29                Yes             3              2           7
19    Male   26                Yes             3              4           6
20    Male   29                Yes             2              4           7
21  Female   24                Yes             2              4           5
22    Male   27                Yes             3              4           6
23    Male   25                Yes             2              4           6
24  Female   26                Yes             2              3           7
25  Female   32                Yes             3              4           7
26    Male   26                Yes             3              4           6
27    Male   31                Yes             2              3           7
28    Male   29                Yes             2              3           6
29  Female   34                Yes             5              4           3
30    Male   27                Yes             4              5           1
31  Female   31                Yes             2              4           7
32    Male   27                Yes             2              4           7
33    Male   26                Yes             2              3           6
34    Male   27                Yes             2              3           6
35    Male   30                Yes             1              4           6
36    Male   30                Yes             2              4           7
37    Male   25                Yes             5              4           7
38    Male   31                Yes             2              4           7
39    Male   29                Yes             4              3           5

    Government_Bonds  Fixed_Deposits  PPF  Gold  ...           Duration  \
0                  3               7    6     4  ...          1-3 years
1                  1               5    6     7  ...  More than 5 years
2                  2               5    1     7  ...          3-5 years
3                  7               6    4     5  ...   Less than 1 year
4                  6               4    5     7  ...   Less than 1 year
5                  6               3    1     2  ...          1-3 years
6                  2               5    1     7  ...          3-5 years
7                  4               6    1     5  ...          3-5 years
8                  5               3    1     6  ...          1-3 years
9                  4               5    2     6  ...          3-5 years
10                 5               3    1     6  ...          3-5 years
11                 6               3    1     4  ...          1-3 years
12                 4               5    6     7  ...          1-3 years
13                 4               5    1     6  ...          1-3 years
14                 5               4    1     6  ...          1-3 years
15                 5               4    1     6  ...          1-3 years
16                 5               4    1     6  ...          1-3 years
17                 4               5    1     6  ...          1-3 years
18                 4               5    1     6  ...          1-3 years
19                 5               1    2     7  ...          3-5 years
20                 5               3    1     6  ...          3-5 years
21                 6               3    1     7  ...          3-5 years
22                 5               2    1     7  ...          3-5 years
23                 5               3    1     7  ...          3-5 years
24                 5               4    1     6  ...          3-5 years
25                 5               1    2     6  ...          3-5 years
26                 5               1    2     7  ...          3-5 years
27                 6               4    1     5  ...          1-3 years
28                 5               1    4     7  ...          1-3 years
29                 2               7    1     6  ...          3-5 years
30                 2               7    3     6  ...          1-3 years
31                 6               3    1     5  ...          3-5 years
32                 5               1    3     6  ...          3-5 years
33                 4               1    5     7  ...          1-3 years
34                 5               4    1     7  ...          1-3 years
35                 5               3    2     7  ...          3-5 years
36                 5               1    3     6  ...          1-3 years
37                 6               1    2     3  ...          3-5 years
38                 5               3    1     6  ...          1-3 years
39                 7               2    1     6  ...          3-5 years

   Invest_Monitor   Expect                 Avenue  \
0         Monthly  20%-30%            Mutual Fund
1          Weekly  20%-30%            Mutual Fund
2           Daily  20%-30%                 Equity
3           Daily  10%-20%                 Equity
4           Daily  20%-30%                 Equity
5           Daily  30%-40%            Mutual Fund
6         Monthly  20%-30%                 Equity
7         Monthly  20%-30%            Mutual Fund
8          Weekly  20%-30%                 Equity
9         Monthly  30%-40%         Fixed Deposits
10        Monthly  20%-30%            Mutual Fund
11        Monthly  20%-30%            Mutual Fund
12         Weekly  20%-30%            Mutual Fund
13        Monthly  20%-30%            Mutual Fund
14        Monthly  20%-30%         Fixed Deposits
15        Monthly  20%-30%            Mutual Fund
16        Monthly  20%-30%         Fixed Deposits
17        Monthly  20%-30%            Mutual Fund
18        Monthly  20%-30%            Mutual Fund
19        Monthly  20%-30%         Fixed Deposits
20         Weekly  20%-30%            Mutual Fund
21        Monthly  20%-30%                 Equity
22        Monthly  20%-30%            Mutual Fund
23         Weekly  20%-30%  Public Provident Fund
24        Monthly  30%-40%  Public Provident Fund
25        Monthly  20%-30%            Mutual Fund
26        Monthly  20%-30%            Mutual Fund
27        Monthly  20%-30%         Fixed Deposits
28        Monthly  20%-30%                 Equity
29        Monthly  10%-20%            Mutual Fund
30        Monthly  10%-20%            Mutual Fund
31        Monthly  20%-30%         Fixed Deposits
32        Monthly  30%-40%                 Equity
33        Monthly  20%-30%         Fixed Deposits
34         Weekly  20%-30%            Mutual Fund
35        Monthly  20%-30%         Fixed Deposits
36        Monthly  20%-30%                 Equity
37        Monthly  30%-40%  Public Provident Fund
38         Weekly  20%-30%                 Equity
39        Monthly  20%-30%         Fixed Deposits

   What are your savings objectives?         Reason_Equity  \
0                    Retirement Plan  Capital Appreciation
1                        Health Care              Dividend
2                    Retirement Plan  Capital Appreciation
3                    Retirement Plan              Dividend
4                    Retirement Plan  Capital Appreciation
5                    Retirement Plan             Liquidity
6                    Retirement Plan  Capital Appreciation
7                    Retirement Plan  Capital Appreciation
8                    Retirement Plan  Capital Appreciation
9                    Retirement Plan  Capital Appreciation
10                   Retirement Plan  Capital Appreciation
11                   Retirement Plan  Capital Appreciation
12                         Education              Dividend
13                   Retirement Plan  Capital Appreciation
14                       Health Care              Dividend
15                       Health Care  Capital Appreciation
16                       Health Care  Capital Appreciation
17                   Retirement Plan  Capital Appreciation
18                   Retirement Plan  Capital Appreciation
19                       Health Care  Capital Appreciation
20                   Retirement Plan  Capital Appreciation
21                       Health Care  Capital Appreciation
22                   Retirement Plan  Capital Appreciation
23                       Health Care             Liquidity
24                   Retirement Plan  Capital Appreciation
25                   Retirement Plan  Capital Appreciation
26                   Retirement Plan              Dividend
27                       Health Care  Capital Appreciation
28                   Retirement Plan  Capital Appreciation
29                   Retirement Plan  Capital Appreciation
30                         Education  Capital Appreciation
31                   Retirement Plan  Capital Appreciation
32                       Health Care  Capital Appreciation
33                         Education              Dividend
34                       Health Care  Capital Appreciation
35                       Health Care  Capital Appreciation
36                   Retirement Plan  Capital Appreciation
37                       Health Care  Capital Appreciation
38                       Health Care              Dividend
39                   Retirement Plan              Dividend

           Reason_Mutual     Reason_Bonds            Reason_FD  \
0         Better Returns  Safe Investment        Fixed Returns
1         Better Returns  Safe Investment  High Interest Rates
2           Tax Benefits  Assured Returns        Fixed Returns
3   Fund Diversification   Tax Incentives  High Interest Rates
4         Better Returns  Safe Investment            Risk Free
5   Fund Diversification  Safe Investment            Risk Free
6         Better Returns  Assured Returns  High Interest Rates
7         Better Returns  Assured Returns            Risk Free
8   Fund Diversification  Safe Investment        Fixed Returns
9   Fund Diversification  Assured Returns        Fixed Returns
10        Better Returns  Assured Returns            Risk Free
11  Fund Diversification  Assured Returns        Fixed Returns
12        Better Returns  Safe Investment            Risk Free
13  Fund Diversification  Assured Returns            Risk Free
14        Better Returns  Assured Returns            Risk Free
15  Fund Diversification  Assured Returns            Risk Free
16  Fund Diversification  Assured Returns            Risk Free
17        Better Returns  Assured Returns            Risk Free
18        Better Returns  Assured Returns            Risk Free
19  Fund Diversification  Assured Returns            Risk Free
20        Better Returns  Assured Returns        Fixed Returns
21        Better Returns  Assured Returns            Risk Free
22        Better Returns  Assured Returns            Risk Free
23        Better Returns  Assured Returns            Risk Free
24        Better Returns  Assured Returns            Risk Free
25        Better Returns  Assured Returns        Fixed Returns
26  Fund Diversification  Assured Returns        Fixed Returns
27  Fund Diversification  Safe Investment        Fixed Returns
28        Better Returns  Assured Returns            Risk Free
29          Tax Benefits  Safe Investment        Fixed Returns
30          Tax Benefits  Safe Investment        Fixed Returns
31        Better Returns  Assured Returns        Fixed Returns
32  Fund Diversification  Assured Returns        Fixed Returns
33        Better Returns  Safe Investment            Risk Free
34        Better Returns  Safe Investment        Fixed Returns
35        Better Returns  Assured Returns        Fixed Returns
36        Better Returns  Assured Returns            Risk Free
37        Better Returns  Safe Investment        Fixed Returns
38  Fund Diversification  Assured Returns        Fixed Returns
39        Better Returns  Safe Investment        Fixed Returns

                      Source
0   Newspapers and Magazines
1      Financial Consultants
2                 Television
3                   Internet
4                   Internet
5                   Internet
6      Financial Consultants
7   Newspapers and Magazines
8                 Television
9   Newspapers and Magazines
10     Financial Consultants
11     Financial Consultants
12                  Internet
13  Newspapers and Magazines
14     Financial Consultants
15  Newspapers and Magazines
16                Television
17     Financial Consultants
18  Newspapers and Magazines
19  Newspapers and Magazines
20     Financial Consultants
21  Newspapers and Magazines
22     Financial Consultants
23     Financial Consultants
24  Newspapers and Magazines
25     Financial Consultants
26     Financial Consultants
27                Television
28                Television
29  Newspapers and Magazines
30                Television
31     Financial Consultants
32  Newspapers and Magazines
33  Newspapers and Magazines
34     Financial Consultants
35     Financial Consultants
36  Newspapers and Magazines
37     Financial Consultants
38  Newspapers and Magazines
39     Financial Consultants

[40 rows x 24 columns]

In [4]:
df.columns

Index(['gender', 'age', 'Investment_Avenues', 'Mutual_Funds', 'Equity_Market',
       'Debentures', 'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold',
       'Stock_Marktet', 'Factor', 'Objective', 'Purpose', 'Duration',
       'Invest_Monitor', 'Expect', 'Avenue',
       'What are your savings objectives?', 'Reason_Equity', 'Reason_Mutual',
       'Reason_Bonds', 'Reason_FD', 'Source'],
      dtype='str')

In [5]:
df.shape

(40, 24)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   gender                             40 non-null     str
 1   age                                40 non-null     int64
 2   Investment_Avenues                 40 non-null     str
 3   Mutual_Funds                       40 non-null     int64
 4   Equity_Market                      40 non-null     int64
 5   Debentures                         40 non-null     int64
 6   Government_Bonds                   40 non-null     int64
 7   Fixed_Deposits                     40 non-null     int64
 8   PPF                                40 non-null     int64
 9   Gold                               40 non-null     int64
 10  Stock_Marktet                      40 non-null     str
 11  Factor                             40 non-null     str
 12  Objective                          40 non-null     str
 13  Purpose                            40 non-null     str
 14  Duration                           40 non-null     str
 15  Invest_Monitor                     40 non-null     str
 16  Expect                             40 non-null     str
 17  Avenue                             40 non-null     str
 18  What are your savings objectives?  40 non-null     str
 19  Reason_Equity                      40 non-null     str
 20  Reason_Mutual                      40 non-null     str
 21  Reason_Bonds                       40 non-null     str
 22  Reason_FD                          40 non-null     str
 23  Source                             40 non-null     str
dtypes: int64(8), str(16)
memory usage: 7.6 KB

In [7]:
df.describe()

,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,27.800000,2.550000,3.475000,5.750000,4.650000,3.575000,2.025000,5.975000
std,3.560467,1.197219,1.131994,1.675617,1.369072,1.795828,1.609069,1.143263
min,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,25.750000,2.000000,3.000000,5.000000,4.000000,2.750000,1.000000,6.000000
50%,27.000000,2.000000,4.000000,6.500000,5.000000,3.500000,1.000000,6.000000
75%,30.000000,3.000000,4.000000,7.000000,5.000000,5.000000,2.250000,7.000000
max,35.000000,7.000000,6.000000,7.000000,7.000000,7.000000,6.000000,7.000000

In [8]:
df.isnull().sum()

gender                               0
age                                  0
Investment_Avenues                   0
Mutual_Funds                         0
Equity_Market                        0
Debentures                           0
Government_Bonds                     0
Fixed_Deposits                       0
PPF                                  0
Gold                                 0
Stock_Marktet                        0
Factor                               0
Objective                            0
Purpose                              0
Duration                             0
Invest_Monitor                       0
Expect                               0
Avenue                               0
What are your savings objectives?    0
Reason_Equity                        0
Reason_Mutual                        0
Reason_Bonds                         0
Reason_FD                            0
Source                               0
dtype: int64

In [10]:
print(df.duplicated().sum())

0

In [25]:
result = df[["gender","age","Investment_Avenues","Objective","Duration","Avenue"]]
print(result)

    gender  age Investment_Avenues             Objective           Duration  \
0   Female   34                Yes  Capital Appreciation          1-3 years
1   Female   23                Yes  Capital Appreciation  More than 5 years
2     Male   30                Yes  Capital Appreciation          3-5 years
3     Male   22                Yes                Income   Less than 1 year
4   Female   24                 No                Income   Less than 1 year
5   Female   24                 No  Capital Appreciation          1-3 years
6   Female   27                Yes  Capital Appreciation          3-5 years
7     Male   21                Yes  Capital Appreciation          3-5 years
8     Male   35                Yes                Growth          1-3 years
9     Male   31                Yes  Capital Appreciation          3-5 years
10  Female   35                Yes                Growth          3-5 years
11    Male   29                Yes  Capital Appreciation          1-3 years
12  Female   21                 No  Capital Appreciation          1-3 years
13  Female   28                Yes  Capital Appreciation          1-3 years
14  Female   25                Yes  Capital Appreciation          1-3 years
15    Male   27                Yes  Capital Appreciation          1-3 years
16  Female   28                Yes                Growth          1-3 years
17    Male   27                Yes  Capital Appreciation          1-3 years
18    Male   29                Yes  Capital Appreciation          1-3 years
19    Male   26                Yes  Capital Appreciation          3-5 years
20    Male   29                Yes                Growth          3-5 years
21  Female   24                Yes  Capital Appreciation          3-5 years
22    Male   27                Yes  Capital Appreciation          3-5 years
23    Male   25                Yes                Growth          3-5 years
24  Female   26                Yes  Capital Appreciation          3-5 years
25  Female   32                Yes                Growth          3-5 years
26    Male   26                Yes  Capital Appreciation          3-5 years
27    Male   31                Yes                Growth          1-3 years
28    Male   29                Yes  Capital Appreciation          1-3 years
29  Female   34                Yes                Income          3-5 years
30    Male   27                Yes                Growth          1-3 years
31  Female   31                Yes  Capital Appreciation          3-5 years
32    Male   27                Yes  Capital Appreciation          3-5 years
33    Male   26                Yes  Capital Appreciation          1-3 years
34    Male   27                Yes  Capital Appreciation          1-3 years
35    Male   30                Yes                Growth          3-5 years
36    Male   30                Yes  Capital Appreciation          1-3 years
37    Male   25                Yes                Growth          3-5 years
38    Male   31                Yes                Growth          1-3 years
39    Male   29                Yes  Capital Appreciation          3-5 years

                   Avenue
0             Mutual Fund
1             Mutual Fund
2                  Equity
3                  Equity
4                  Equity
5             Mutual Fund
6                  Equity
7             Mutual Fund
8                  Equity
9          Fixed Deposits
10            Mutual Fund
11            Mutual Fund
12            Mutual Fund
13            Mutual Fund
14         Fixed Deposits
15            Mutual Fund
16         Fixed Deposits
17            Mutual Fund
18            Mutual Fund
19         Fixed Deposits
20            Mutual Fund
21                 Equity
22            Mutual Fund
23  Public Provident Fund
24  Public Provident Fund
25            Mutual Fund
26            Mutual Fund
27         Fixed Deposits
28                 Equity
29            Mutual Fund
30            Mutual Fund
31         Fixed Deposits
32                 Equity
33         Fixed Deposits
34            Mutual Fund
35         Fixed Deposits
36                 Equity
37  Public Provident Fund
38                 Equity
39         Fixed Deposits

In [17]:
result=df.loc[df["age"]>30,["gender","age","Avenue","Objective"]]
print(result)

    gender  age          Avenue             Objective
0   Female   34     Mutual Fund  Capital Appreciation
8     Male   35          Equity                Growth
9     Male   31  Fixed Deposits  Capital Appreciation
10  Female   35     Mutual Fund                Growth
25  Female   32     Mutual Fund                Growth
27    Male   31  Fixed Deposits                Growth
29  Female   34     Mutual Fund                Income
31  Female   31  Fixed Deposits  Capital Appreciation
38    Male   31          Equity                Growth

In [18]:
result=df.loc[(df["gender"]=="Female")& (df["age"]>30),["age","Avenue","Duration"]]
print(result)

    age          Avenue   Duration
0    34     Mutual Fund  1-3 years
10   35     Mutual Fund  3-5 years
25   32     Mutual Fund  3-5 years
29   34     Mutual Fund  3-5 years
31   31  Fixed Deposits  3-5 years

In [27]:
result=df.loc[df["Avenue"]=="Equity",["gender","age","Objective","Avenue","Duration"]]
print(result)

    gender  age             Objective  Avenue          Duration
2     Male   30  Capital Appreciation  Equity         3-5 years
3     Male   22                Income  Equity  Less than 1 year
4   Female   24                Income  Equity  Less than 1 year
6   Female   27  Capital Appreciation  Equity         3-5 years
8     Male   35                Growth  Equity         1-3 years
21  Female   24  Capital Appreciation  Equity         3-5 years
28    Male   29  Capital Appreciation  Equity         1-3 years
32    Male   27  Capital Appreciation  Equity         3-5 years
36    Male   30  Capital Appreciation  Equity         1-3 years
38    Male   31                Growth  Equity         1-3 years

In [28]:
print("Source"in df.columns)

False

In [29]:
import pandas as pd
df=pd.read_csv("Finance_data.csv")
df.head()

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Female,34,Yes,1,2,5,3,7,6,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines
1,Female,23,Yes,4,3,2,1,5,6,7,...,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants
2,Male,30,Yes,3,6,4,2,5,1,7,...,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television
3,Male,22,Yes,2,1,3,7,6,4,5,...,Less than 1 year,Daily,10%-20%,Equity,Retirement Plan,Dividend,Fund Diversification,Tax Incentives,High Interest Rates,Internet
4,Female,24,No,2,1,3,6,4,5,7,...,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Risk Free,Internet

In [30]:
print(df.shape)

(40, 24)

In [31]:
print(df.columns.tolist())

['gender', 'age', 'Investment_Avenues', 'Mutual_Funds', 'Equity_Market', 'Debentures', 'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold', 'Stock_Marktet', 'Factor', 'Objective', 'Purpose', 'Duration', 'Invest_Monitor', 'Expect', 'Avenue', 'What are your savings objectives?', 'Reason_Equity', 'Reason_Mutual', 'Reason_Bonds', 'Reason_FD', 'Source']

In [32]:
result=df.loc[df["Avenue"]=="Equity",["gender","age","Objective","Avenue","Duration","Source"]]
print(result)

    gender  age             Objective  Avenue          Duration  \
2     Male   30  Capital Appreciation  Equity         3-5 years
3     Male   22                Income  Equity  Less than 1 year
4   Female   24                Income  Equity  Less than 1 year
6   Female   27  Capital Appreciation  Equity         3-5 years
8     Male   35                Growth  Equity         1-3 years
21  Female   24  Capital Appreciation  Equity         3-5 years
28    Male   29  Capital Appreciation  Equity         1-3 years
32    Male   27  Capital Appreciation  Equity         3-5 years
36    Male   30  Capital Appreciation  Equity         1-3 years
38    Male   31                Growth  Equity         1-3 years

                      Source
2                 Television
3                   Internet
4                   Internet
6      Financial Consultants
8                 Television
21  Newspapers and Magazines
28                Television
32  Newspapers and Magazines
36  Newspapers and Magazines
38  Newspapers and Magazines

In [34]:
result=df.loc[(df["Investment_Avenues"]=="Yes")& (df["Stock_Marktet"]=="Yes"),["gender","age","Avenue","Objective"]]
print(result)

    gender  age                 Avenue             Objective
0   Female   34            Mutual Fund  Capital Appreciation
2     Male   30                 Equity  Capital Appreciation
3     Male   22                 Equity                Income
6   Female   27                 Equity  Capital Appreciation
7     Male   21            Mutual Fund  Capital Appreciation
8     Male   35                 Equity                Growth
9     Male   31         Fixed Deposits  Capital Appreciation
10  Female   35            Mutual Fund                Growth
11    Male   29            Mutual Fund  Capital Appreciation
13  Female   28            Mutual Fund  Capital Appreciation
14  Female   25         Fixed Deposits  Capital Appreciation
15    Male   27            Mutual Fund  Capital Appreciation
16  Female   28         Fixed Deposits                Growth
17    Male   27            Mutual Fund  Capital Appreciation
18    Male   29            Mutual Fund  Capital Appreciation
19    Male   26         Fixed Deposits  Capital Appreciation
20    Male   29            Mutual Fund                Growth
21  Female   24                 Equity  Capital Appreciation
22    Male   27            Mutual Fund  Capital Appreciation
23    Male   25  Public Provident Fund                Growth
24  Female   26  Public Provident Fund  Capital Appreciation
25  Female   32            Mutual Fund                Growth
26    Male   26            Mutual Fund  Capital Appreciation
27    Male   31         Fixed Deposits                Growth
28    Male   29                 Equity  Capital Appreciation
29  Female   34            Mutual Fund                Income
31  Female   31         Fixed Deposits  Capital Appreciation
32    Male   27                 Equity  Capital Appreciation
33    Male   26         Fixed Deposits  Capital Appreciation
34    Male   27            Mutual Fund  Capital Appreciation
35    Male   30         Fixed Deposits                Growth
36    Male   30                 Equity  Capital Appreciation
37    Male   25  Public Provident Fund                Growth
38    Male   31                 Equity                Growth
39    Male   29         Fixed Deposits  Capital Appreciation

In [38]:
result=df.loc[df["Expect"]=="20%-30%"]
print(result)

    gender  age Investment_Avenues  Mutual_Funds  Equity_Market  Debentures  \
0   Female   34                Yes             1              2           5
1   Female   23                Yes             4              3           2
2     Male   30                Yes             3              6           4
4   Female   24                 No             2              1           3
6   Female   27                Yes             3              6           4
7     Male   21                Yes             2              3           7
8     Male   35                Yes             2              4           7
10  Female   35                Yes             2              4           7
11    Male   29                Yes             2              5           7
12  Female   21                 No             1              2           3
13  Female   28                Yes             2              3           7
14  Female   25                Yes             2              3           7
15    Male   27                Yes             2              3           7
16  Female   28                Yes             3              2           7
17    Male   27                Yes             3              2           7
18    Male   29                Yes             3              2           7
19    Male   26                Yes             3              4           6
20    Male   29                Yes             2              4           7
21  Female   24                Yes             2              4           5
22    Male   27                Yes             3              4           6
23    Male   25                Yes             2              4           6
25  Female   32                Yes             3              4           7
26    Male   26                Yes             3              4           6
27    Male   31                Yes             2              3           7
28    Male   29                Yes             2              3           6
31  Female   31                Yes             2              4           7
33    Male   26                Yes             2              3           6
34    Male   27                Yes             2              3           6
35    Male   30                Yes             1              4           6
36    Male   30                Yes             2              4           7
38    Male   31                Yes             2              4           7
39    Male   29                Yes             4              3           5

    Government_Bonds  Fixed_Deposits  PPF  Gold  ...           Duration  \
0                  3               7    6     4  ...          1-3 years
1                  1               5    6     7  ...  More than 5 years
2                  2               5    1     7  ...          3-5 years
4                  6               4    5     7  ...   Less than 1 year
6                  2               5    1     7  ...          3-5 years
7                  4               6    1     5  ...          3-5 years
8                  5               3    1     6  ...          1-3 years
10                 5               3    1     6  ...          3-5 years
11                 6               3    1     4  ...          1-3 years
12                 4               5    6     7  ...          1-3 years
13                 4               5    1     6  ...          1-3 years
14                 5               4    1     6  ...          1-3 years
15                 5               4    1     6  ...          1-3 years
16                 5               4    1     6  ...          1-3 years
17                 4               5    1     6  ...          1-3 years
18                 4               5    1     6  ...          1-3 years
19                 5               1    2     7  ...          3-5 years
20                 5               3    1     6  ...          3-5 years
21                 6               3    1     7  ...          3-5 years
22                 5               2    1     7  ...          3-5 years
23                 5               3    1     7  ...          3-5 years
25                 5               1    2     6  ...          3-5 years
26                 5               1    2     7  ...          3-5 years
27                 6               4    1     5  ...          1-3 years
28                 5               1    4     7  ...          1-3 years
31                 6               3    1     5  ...          3-5 years
33                 4               1    5     7  ...          1-3 years
34                 5               4    1     7  ...          1-3 years
35                 5               3    2     7  ...          3-5 years
36                 5               1    3     6  ...          1-3 years
38                 5               3    1     6  ...          1-3 years
39                 7               2    1     6  ...          3-5 years

   Invest_Monitor   Expect                 Avenue  \
0         Monthly  20%-30%            Mutual Fund
1          Weekly  20%-30%            Mutual Fund
2           Daily  20%-30%                 Equity
4           Daily  20%-30%                 Equity
6         Monthly  20%-30%                 Equity
7         Monthly  20%-30%            Mutual Fund
8          Weekly  20%-30%                 Equity
10        Monthly  20%-30%            Mutual Fund
11        Monthly  20%-30%            Mutual Fund
12         Weekly  20%-30%            Mutual Fund
13        Monthly  20%-30%            Mutual Fund
14        Monthly  20%-30%         Fixed Deposits
15        Monthly  20%-30%            Mutual Fund
16        Monthly  20%-30%         Fixed Deposits
17        Monthly  20%-30%            Mutual Fund
18        Monthly  20%-30%            Mutual Fund
19        Monthly  20%-30%         Fixed Deposits
20         Weekly  20%-30%            Mutual Fund
21        Monthly  20%-30%                 Equity
22        Monthly  20%-30%            Mutual Fund
23         Weekly  20%-30%  Public Provident Fund
25        Monthly  20%-30%            Mutual Fund
26        Monthly  20%-30%            Mutual Fund
27        Monthly  20%-30%         Fixed Deposits
28        Monthly  20%-30%                 Equity
31        Monthly  20%-30%         Fixed Deposits
33        Monthly  20%-30%         Fixed Deposits
34         Weekly  20%-30%            Mutual Fund
35        Monthly  20%-30%         Fixed Deposits
36        Monthly  20%-30%                 Equity
38         Weekly  20%-30%                 Equity
39        Monthly  20%-30%         Fixed Deposits

   What are your savings objectives?         Reason_Equity  \
0                    Retirement Plan  Capital Appreciation
1                        Health Care              Dividend
2                    Retirement Plan  Capital Appreciation
4                    Retirement Plan  Capital Appreciation
6                    Retirement Plan  Capital Appreciation
7                    Retirement Plan  Capital Appreciation
8                    Retirement Plan  Capital Appreciation
10                   Retirement Plan  Capital Appreciation
11                   Retirement Plan  Capital Appreciation
12                         Education              Dividend
13                   Retirement Plan  Capital Appreciation
14                       Health Care              Dividend
15                       Health Care  Capital Appreciation
16                       Health Care  Capital Appreciation
17                   Retirement Plan  Capital Appreciation
18                   Retirement Plan  Capital Appreciation
19                       Health Care  Capital Appreciation
20                   Retirement Plan  Capital Appreciation
21                       Health Care  Capital Appreciation
22                   Retirement Plan  Capital Appreciation
23                       Health Care             Liquidity
25                   Retirement Plan  Capital Appreciation
26                   Retirement Plan              Dividend
27                       Health Care  Capital Appreciation
28                   Retirement Plan  Capital Appreciation
31                   Retirement Plan  Capital Appreciation
33                         Education              Dividend
34                       Health Care  Capital Appreciation
35                       Health Care  Capital Appreciation
36                   Retirement Plan  Capital Appreciation
38                       Health Care              Dividend
39                   Retirement Plan              Dividend

           Reason_Mutual     Reason_Bonds            Reason_FD  \
0         Better Returns  Safe Investment        Fixed Returns
1         Better Returns  Safe Investment  High Interest Rates
2           Tax Benefits  Assured Returns        Fixed Returns
4         Better Returns  Safe Investment            Risk Free
6         Better Returns  Assured Returns  High Interest Rates
7         Better Returns  Assured Returns            Risk Free
8   Fund Diversification  Safe Investment        Fixed Returns
10        Better Returns  Assured Returns            Risk Free
11  Fund Diversification  Assured Returns        Fixed Returns
12        Better Returns  Safe Investment            Risk Free
13  Fund Diversification  Assured Returns            Risk Free
14        Better Returns  Assured Returns            Risk Free
15  Fund Diversification  Assured Returns            Risk Free
16  Fund Diversification  Assured Returns            Risk Free
17        Better Returns  Assured Returns            Risk Free
18        Better Returns  Assured Returns            Risk Free
19  Fund Diversification  Assured Returns            Risk Free
20        Better Returns  Assured Returns        Fixed Returns
21        Better Returns  Assured Returns            Risk Free
22        Better Returns  Assured Returns            Risk Free
23        Better Returns  Assured Returns            Risk Free
25        Better Returns  Assured Returns        Fixed Returns
26  Fund Diversification  Assured Returns        Fixed Returns
27  Fund Diversification  Safe Investment        Fixed Returns
28        Better Returns  Assured Returns            Risk Free
31        Better Returns  Assured Returns        Fixed Returns
33        Better Returns  Safe Investment            Risk Free
34        Better Returns  Safe Investment        Fixed Returns
35        Better Returns  Assured Returns        Fixed Returns
36        Better Returns  Assured Returns            Risk Free
38  Fund Diversification  Assured Returns        Fixed Returns
39        Better Returns  Safe Investment        Fixed Returns

                      Source
0   Newspapers and Magazines
1      Financial Consultants
2                 Television
4                   Internet
6      Financial Consultants
7   Newspapers and Magazines
8                 Television
10     Financial Consultants
11     Financial Consultants
12                  Internet
13  Newspapers and Magazines
14     Financial Consultants
15  Newspapers and Magazines
16                Television
17     Financial Consultants
18  Newspapers and Magazines
19  Newspapers and Magazines
20     Financial Consultants
21  Newspapers and Magazines
22     Financial Consultants
23     Financial Consultants
25     Financial Consultants
26     Financial Consultants
27                Television
28                Television
31     Financial Consultants
33  Newspapers and Magazines
34     Financial Consultants
35     Financial Consultants
36  Newspapers and Magazines
38  Newspapers and Magazines
39     Financial Consultants

[32 rows x 24 columns]